#!/bin/bash

. ~solson/.bashrc
ruby /home/solson/switch-tracker/switch.rb >> /home/solson/switch-tracker/switch-log.txt
# echo "ran at:" >> /home/solson/switch-tracker/jobs-log.txt
# date >> /home/solson/switch-tracker/jobs-log.txt
